version: '2'
services:

  redis:
    image: redis:latest
    container_name: rd01
    ports:
     - '6379:6379'

  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - /static:/static

    depends_on:
      - web

  celery:
    build: .
    container_name: cl01
    command: celery -A rsscatcher worker -B  -l debug
    volumes:
      - ./src:/src
    links:
      - redis

  web:
    build: .
    container_name: dg01
    command: bash -c "python manage.py makemigrations && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py loaddata fixtures.json && gunicorn rsscatcher.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - ./src:/src
      - /static:/static 
    expose:
      - "8000"

  db:
    image: postgres:latest
    container_name: ps01